project_id = "iwremcrvzoprfrytvoze"

[functions.process-paystack]
verify_jwt = true

[functions.process-paypal]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.webhook-paystack]
verify_jwt = false

[functions.webhook-paypal]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.generate-certificate]
verify_jwt = true

[functions.check-price-alerts]
verify_jwt = false
